language: r
latex: false
fortran: false

matrix:
  include:
    - dist: xenial
      addons:
        apt:
          packages: libv8-dev
    - dist: xenial
      addons:
        apt:
          packages: libnode-dev
      r_packages: covr
      after_success: Rscript -e 'covr::codecov()'
    - os: osx
